# Generated by Django 5.1 on 2024-08-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='json',
            name='nombre',
            field=models.CharField(max_length=5),
        ),
    ]
