# Generated by Django 5.1 on 2024-08-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_json_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='json',
            old_name='cantidad_max',
            new_name='averageafter',
        ),
        migrations.RenameField(
            model_name='json',
            old_name='cantidad_min',
            new_name='averagebefore',
        ),
        migrations.RenameField(
            model_name='json',
            old_name='descripcion',
            new_name='devicename',
        ),
        migrations.RemoveField(
            model_name='json',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='json',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='json',
            name='precio',
        ),
        migrations.AddField(
            model_name='json',
            name='datasize',
            field=models.IntegerField(default=0, verbose_name='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='json',
            name='rawdata',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
